# <font color='blue'>Array e Soma Acumulada</font>


In [13]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.8.5


In [14]:
# Importando o NumPy
import numpy as np

In [15]:
# Versão do Numpy
np.__version__

'1.19.2'

## Criando Arrays

In [16]:
# Array criado a partir de uma lista:
vetor1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

#Exibindo Array
print(vetor1)

[0 1 2 3 4 5 6 7 8]


In [17]:
# Um objeto do tipo ndarray é um recipiente multidimensional de itens do mesmo tipo e tamanho.
type(vetor1)

numpy.ndarray

## Soma Acumulada

In [18]:
# SOMA ACUMULADA
vetor1.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [19]:
# Imprimindo na tela um elemento específico no array
vetor1[2] 

2

In [20]:
# Alterando um elemento do array (mudando o valor 2)
vetor1[2] = 100

In [21]:
print(vetor1)

[  0   1 100   3   4   5   6   7   8]


In [22]:
# Verificando o formato do array
print(vetor1.shape)

(9,)


In [24]:
#Soma Acumulada -> agora usando com o valor 2 alterado para 100
vetor1.cumsum()

array([  0,   1, 101, 104, 108, 113, 119, 126, 134], dtype=int32)