# <font color='blue'>Numpy</font>


In [2]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.8.5


In [3]:
# Importando o NumPy
import numpy as np

In [4]:
# Versão do Numpy
np.__version__

'1.19.2'

## Funções NumPy

In [5]:
# A função arange cria um vetor contendo uma progressão aritmética a partir de um intervalo -
#np.arange (número inicial, número final, numero que vai acrescentando ou somando)

vetor2 = np.arange(0.0, 2.25 ,0.25 )

In [6]:
print(vetor2)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [7]:
# Verificando o tipo do objeto
type(vetor2)

numpy.ndarray

In [8]:
# Formato do array (unidimencional)
np.shape(vetor2)

(9,)

In [21]:
# FLOAT, pois tem casa decimal
print (vetor2.dtype)

float64


In [9]:
x = np.arange(1, 10, 0.25)
print(x)

[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.   4.25
 4.5  4.75 5.   5.25 5.5  5.75 6.   6.25 6.5  6.75 7.   7.25 7.5  7.75
 8.   8.25 8.5  8.75 9.   9.25 9.5  9.75]


In [10]:
# Crima uma lista de peso em uma rede neural profunda (deep learning) 
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
# Retorna 1 nas posições em diagonal e 0 no restante
z = np.eye(3)

In [12]:
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# Os valores passados como parâmetro, formam uma diagonal
d = np.diag(np.array([1, 2, 3, 4]))

In [14]:
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [15]:
# Array de números complexos
c = np.array([1+2j, 3+4j, 5+6*1j])

In [16]:
c

array([1.+2.j, 3.+4.j, 5.+6.j])

In [17]:
# Array de valores booleanos
b = np.array([True, False, False, True])

In [18]:
b

array([ True, False, False,  True])

In [19]:
# Array de strings
s = np.array(['Python', 'para', 'Ciência','de','Dados'])

In [20]:
s

array(['Python', 'para', 'Ciência', 'de', 'Dados'], dtype='<U7')

In [24]:
# O método linspace (linearly spaced vector) retorna um número de 
# valores igualmente distribuídos no intervalo especificado 
np.linspace(0, 5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [29]:
#Lista de 0 a 10, "dividido" em 11 números
print(np.linspace(0, 10, 11))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [31]:
#Lista de 0 a 10, "dividido" em 5 números
print(np.linspace(0, 10, 5))

[ 0.   2.5  5.   7.5 10. ]


In [33]:
print(np.logspace(0, 10, 11))

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09
 1.e+10]
