# <font color='blue'>Numpy</font>


In [3]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.8.5


In [4]:
# Importando o NumPy
import numpy as np

In [5]:
# Versão do Numpy
np.__version__

'1.19.2'

## Criando Matrizes

In [6]:
# Criando uma matriz
matriz = np.array([[2,4,6],[3,5,7]]) 

In [7]:
print(matriz)

[[2 4 6]
 [3 5 7]]


In [22]:
#Exibir Número de Linhas (2) e número de Colunas (3)
print(matriz.shape)

(2, 3)


In [23]:
# Criando uma matriz 2x3 apenas com números "1"
matriz1 = np.ones((2,3))

In [24]:
print(matriz1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [26]:
# Criando uma matriz a partir de uma lista de listas
lista = [[13,81,22], [0, 34, 59], [21, 48, 94]]


[[13, 81, 22], [0, 34, 59], [21, 48, 94]]


## Transformando Lista em Matriz
<i> É necessário transformar lista em Matriz, pois existe muito recursos matemáticos na Matriz que não tem na Lista</i>

In [44]:
# A função matrix cria uma matria a partir de uma sequência
matriz2 = np.matrix(lista)

In [45]:
matriz2

matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

In [46]:
type(matriz2)

numpy.matrix

In [47]:
# Formato da matriz
np.shape(matriz2)

(3, 3)

In [48]:
# Total Numero de Linhas(3)x Número de Colunas (3) = 9 
matriz2.size

9

In [49]:
print(matriz2.dtype)

int32


In [50]:
matriz2.itemsize

4

In [34]:
# Tamno em Bytes
matriz2.nbytes

36

In [35]:
#Exibindo item da linha 2 e coluna 1
print(matriz2[2,1])

48


In [37]:
# Alterando um elemento da matriz
matriz2[1,0] = 100
matriz2[2,1] = 1

In [38]:
matriz2

matrix([[ 13,  81,  22],
        [100,  34,  59],
        [ 21,   1,  94]])

In [54]:
x = np.array([1, 2])  # NumPy decide o tipo dos dados (Todos são inteiros)
y = np.array([1.0, 2.0])  # NumPy decide o tipo dos dados (Todos são Floats)
z = np.array([1, 2], dtype=np.float64)  # Forçamos um tipo de dado (São inteiros mas forçamos, dizendo que é float)

print (x.dtype, y.dtype, z.dtype)

int64 float64 float64


In [55]:
matriz3 = np.array([[24, 76], [35, 89]], dtype=float)

In [56]:
matriz3

array([[24., 76.],
       [35., 89.]])

In [57]:
#Tamanho de cada item
matriz3.itemsize

8

In [58]:
# Tamanho em Bytes
matriz3.nbytes

32

In [59]:
# Número de Dimênsões matriz3.ndim

2

In [60]:
#Exibir o item que está na linha 1 e na coluna 1
matriz3[1,1]

89.0

In [61]:
#Alterar o valor da linha e coluna 1 para 100
matriz3[1,1] = 100

In [62]:
matriz3

array([[ 24.,  76.],
       [ 35., 100.]])

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>